"""changed column names

Revision ID: 2945707ec35e
Revises: f39e40161613
Create Date: 2025-01-09 12:47:50.402039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2945707ec35e'
down_revision: Union[str, None] = 'f39e40161613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotaract_students', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('rotaract_students', sa.Column('startYear', sa.Integer(), nullable=False))
    op.add_column('rotaract_students', sa.Column('endYear', sa.Integer(), nullable=True))
    op.add_column('rotaract_students', sa.Column('mobileNo', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_rotaract_students_name'), 'rotaract_students', ['name'], unique=False)
    op.drop_column('rotaract_students', 'end_year')
    op.drop_column('rotaract_students', 'mobile_no')
    op.drop_column('rotaract_students', 'start_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotaract_students', sa.Column('start_year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rotaract_students', sa.Column('mobile_no', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('rotaract_students', sa.Column('end_year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_rotaract_students_name'), table_name='rotaract_students')
    op.drop_column('rotaract_students', 'mobileNo')
    op.drop_column('rotaract_students', 'endYear')
    op.drop_column('rotaract_students', 'startYear')
    op.drop_column('rotaract_students', 'name')
    # ### end Alembic commands ###
