"""Create Rotaract_Students table

Revision ID: d43f342b2d63
Revises: 
Create Date: 2024-12-21 00:00:27.232143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43f342b2d63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rotaract_Students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dept', sa.String(), nullable=True),
    sa.Column('startYear', sa.Integer(), nullable=True),
    sa.Column('endYear', sa.Integer(), nullable=True),
    sa.Column('mobileNo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Rotaract_Students_email'), 'Rotaract_Students', ['email'], unique=True)
    op.create_index(op.f('ix_Rotaract_Students_id'), 'Rotaract_Students', ['id'], unique=False)
    op.create_index(op.f('ix_Rotaract_Students_name'), 'Rotaract_Students', ['name'], unique=False)
    op.create_index(op.f('ix_Rotaract_Students_roll_no'), 'Rotaract_Students', ['roll_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Rotaract_Students_roll_no'), table_name='Rotaract_Students')
    op.drop_index(op.f('ix_Rotaract_Students_name'), table_name='Rotaract_Students')
    op.drop_index(op.f('ix_Rotaract_Students_id'), table_name='Rotaract_Students')
    op.drop_index(op.f('ix_Rotaract_Students_email'), table_name='Rotaract_Students')
    op.drop_table('Rotaract_Students')
    # ### end Alembic commands ###
